version: '3.3'
    
services:
  score:
    build: .
    ports:
        - 5051:5051
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]